In [1]:
text= 'hare krishna hari bol'

In [2]:
text.split()

['hare', 'krishna', 'hari', 'bol']

In [3]:
print(text.split())

['hare', 'krishna', 'hari', 'bol']


In [11]:
for item in text:
    print(item)
    print ('.....')
    if text.strip():
        # print (item.strip())
        # print(item)
        

_IncompleteInputError: incomplete input (1554310185.py, line 7)

In [13]:
l = [1,2,3,4]
l.extend([5,6,7])
l

[1, 2, 3, 4, 5, 6, 7]

In [15]:
s = (1,2,3)
l.extend(s)
l

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 1, 2, 3]

In [6]:
# lets code the attn so that i can revise what we did yesterday
import torch
inputs = torch.tensor(
    [[0.43,0.15,0.89], #your
     [0.55,0.87,0.66],#journey
     [0.57,0.85,0.64],#starts
     [0.22,0.58,0.33],
     [0.77,0.25,0.10],
     [0.05,0.80,0.55]]
)
print(inputs.shape)
print(inputs.T)

torch.Size([6, 3])
tensor([[0.4300, 0.5500, 0.5700, 0.2200, 0.7700, 0.0500],
        [0.1500, 0.8700, 0.8500, 0.5800, 0.2500, 0.8000],
        [0.8900, 0.6600, 0.6400, 0.3300, 0.1000, 0.5500]])


In [7]:
# first we have to find the scores, then attn wts(using softmax)
attn_scores= torch.empty(inputs.shape)
attn_scores

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
attn_scores= inputs @ inputs.T
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [12]:
attn_wts= torch.softmax(attn_scores, dim= 1)
attn_wts

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [13]:
print(attn_wts[0].sum())

tensor(1.0000)


hmm. now we have got the attn wtw, now we need to get the context vector. oh wait well i forgot to add q,k,v... lets do that in some time

In [14]:
context= torch.empty(inputs.shape)


In [17]:
context = attn_wts @ inputs
context 

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

i think thats it!

## now lets do self attention with q k v (traninable)

In [19]:
inputs.shape

torch.Size([6, 3])

In [20]:
# he told that the size of q ,k, v can be anything. but dq= dk 
din = 3 # input features
dout = 4
Wq= torch.nn.Linear(din, dout)
Wk= torch.nn.Linear(din, dout)
Wv= torch.nn.Linear(din, dout)
# now we have made the layers
 


In [21]:
attn_scores= torch.dot(Wq, Wk)

TypeError: dot(): argument 'input' (position 1) must be Tensor, not Linear

In [22]:
class Animal:

    def __init__(self):
        print("Animal created")

class Dog(Animal):

    def __init__(self):
        super().__init__()
        print("Dog created")

In [23]:
d= Dog()

Animal created
Dog created
