In [1]:
text= 'hare krishna hari bol'

In [2]:
text.split()

['hare', 'krishna', 'hari', 'bol']

In [3]:
print(text.split())

['hare', 'krishna', 'hari', 'bol']


In [11]:
for item in text:
    print(item)
    print ('.....')
    if text.strip():
        # print (item.strip())
        # print(item)
        

_IncompleteInputError: incomplete input (1554310185.py, line 7)

In [13]:
l = [1,2,3,4]
l.extend([5,6,7])
l

[1, 2, 3, 4, 5, 6, 7]

In [15]:
s = (1,2,3)
l.extend(s)
l

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 1, 2, 3]

In [6]:
# lets code the attn so that i can revise what we did yesterday
import torch
inputs = torch.tensor(
    [[0.43,0.15,0.89], #your
     [0.55,0.87,0.66],#journey
     [0.57,0.85,0.64],#starts
     [0.22,0.58,0.33],
     [0.77,0.25,0.10],
     [0.05,0.80,0.55]]
)
print(inputs.shape)
print(inputs.T)

torch.Size([6, 3])
tensor([[0.4300, 0.5500, 0.5700, 0.2200, 0.7700, 0.0500],
        [0.1500, 0.8700, 0.8500, 0.5800, 0.2500, 0.8000],
        [0.8900, 0.6600, 0.6400, 0.3300, 0.1000, 0.5500]])


In [7]:
# first we have to find the scores, then attn wts(using softmax)
attn_scores= torch.empty(inputs.shape)
attn_scores

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
attn_scores= inputs @ inputs.T
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [12]:
attn_wts= torch.softmax(attn_scores, dim= 1)
attn_wts

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [13]:
print(attn_wts[0].sum())

tensor(1.0000)


hmm. now we have got the attn wtw, now we need to get the context vector. oh wait well i forgot to add q,k,v... lets do that in some time

In [14]:
context= torch.empty(inputs.shape)


In [17]:
context = attn_wts @ inputs
context 

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

i think thats it!

## now lets do self attention with q k v (traninable)

In [19]:
inputs.shape

torch.Size([6, 3])

In [20]:
# he told that the size of q ,k, v can be anything. but dq= dk 
din = 3 # input features
dout = 4
Wq= torch.nn.Linear(din, dout)
Wk= torch.nn.Linear(din, dout)
Wv= torch.nn.Linear(din, dout)
# now we have made the layers
 


In [21]:
attn_scores= torch.dot(Wq, Wk)

TypeError: dot(): argument 'input' (position 1) must be Tensor, not Linear

In [22]:
class Animal:

    def __init__(self):
        print("Animal created")

class Dog(Animal):

    def __init__(self):
        super().__init__()
        print("Dog created")

In [23]:
d= Dog()

Animal created
Dog created


In [1]:
import torch

In [48]:

hari = torch.rand(2,3,2,3)
hari.shape

torch.Size([2, 3, 2, 3])

In [49]:

x = hari.numel()
x

36

In [119]:
result = torch.arange(x).view(hari.shape)
# result

TypeError: arange(): argument 'end' (position 1) must be Number, not Tensor

In [53]:
result= result.view(2,2,3,3)
result

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],

         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]]])

In [120]:
result= result.view(9,1,2,2)
# result

In [57]:
result[0]

tensor([[[0, 1],
         [2, 3]]])

In [121]:
x = torch.arange(4*3*2*2).view(4,3,2,2)
# x

In [66]:
x= x.transpose(0,1)
x.shape

torch.Size([3, 4, 2, 2])

In [122]:
# x

In [123]:
y = torch.arange(4*3*2*2).view(4,3,2,2)
# y

In [69]:
y=y.view(3,4,2,2)
y

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]],


        [[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]],

         [[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]],


        [[[32, 33],
          [34, 35]],

         [[36, 37],
          [38, 39]],

         [[40, 41],
          [42, 43]],

         [[44, 45],
          [46, 47]]]])

In [71]:
y = torch.arange(2*4*3).view(2,4,3)
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [72]:
print(y.transpose(-2,-1))

tensor([[[ 0,  3,  6,  9],
         [ 1,  4,  7, 10],
         [ 2,  5,  8, 11]],

        [[12, 15, 18, 21],
         [13, 16, 19, 22],
         [14, 17, 20, 23]]])


In [73]:
print(y.transpose(0,1))

tensor([[[ 0,  1,  2],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [15, 16, 17]],

        [[ 6,  7,  8],
         [18, 19, 20]],

        [[ 9, 10, 11],
         [21, 22, 23]]])


In [74]:
print(y.view(4,2,3))

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])


In [75]:
print(y.reshape(4,2,3))

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])


In [94]:
hari= torch.arange(4*4).view(4,4)

In [95]:
mask = torch.triu(torch.ones(4,4), diagonal =2)
mask.bool()

tensor([[False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [100]:
masked = hari.float().masked_fill(mask.bool(), -torch.inf)
masked

tensor([[ 0.,  1., -inf, -inf],
        [ 4.,  5.,  6., -inf],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [101]:
torch.manual_seed(123)
paksh_chaya= torch.nn.Dropout(0.5)
krishna= torch.ones(6,6)
print(hari)
print(paksh_chaya(krishna))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])


In [102]:
print(paksh_chaya(masked))

tensor([[ 0.,  0., nan, nan],
        [ 0.,  0.,  0., nan],
        [16.,  0., 20., 22.],
        [ 0., 26., 28., 30.]])


In [103]:
hari

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [116]:
radha =torch.stack((hari,hari, hari), dim =0)

In [118]:
radha.shape

torch.Size([3, 4, 4])

In [124]:
y= torch.arange(4*3*4).view(2,3,2,4).float()
print(y.dtype)
print(y)

torch.float32
tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]],

         [[ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.]]],


        [[[24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.]],

         [[40., 41., 42., 43.],
          [44., 45., 46., 47.]]]])


In [ ]:
hari= torch.nn.Linear(4,5)

In [ ]:
print(hari(y))

In [130]:
radhe = [1,2,3,4,5]
print(type(radhe))

<class 'list'>


In [ ]:
print(*radhe)
print(type(radhe))


1 2 3 4 5
<class 'list'>


TypeError: type() takes 1 or 3 arguments

In [134]:
L= [1,2,3]

In [135]:
print(L)

[1, 2, 3]


In [136]:
print(*L)

1 2 3


In [145]:
def hari(x,y,z):
    print("hare krishna")
    print(x,y,z)

radha= [1,22,3]
# for _ in range(*radha):
hari(*radha) 

hare krishna
1 22 3


In [147]:
print("radha") for _ in range(3)

SyntaxError: invalid syntax (2322089875.py, line 1)

In [148]:
gen = (i*i for i in range(3))

print(gen)

<generator object <genexpr> at 0x000001D6805331D0>


In [151]:
subala= torch.rand(2*3*5).view(2,3,5)
subala


tensor([[[0.9221, 0.9043, 0.5713, 0.9546, 0.8339],
         [0.8730, 0.4675, 0.1163, 0.4938, 0.5938],
         [0.1594, 0.2132, 0.0206, 0.3247, 0.9355]],

        [[0.5855, 0.4695, 0.5201, 0.8118, 0.0585],
         [0.1142, 0.3338, 0.2122, 0.7579, 0.8533],
         [0.0149, 0.0757, 0.0131, 0.6886, 0.9024]]])

In [157]:
mean= subala.mean(dim=1, keepdim= True)
print(mean)
print(mean.shape)

tensor([[[0.6515, 0.5283, 0.2361, 0.5910, 0.7877]],

        [[0.2382, 0.2930, 0.2485, 0.7528, 0.6047]]])
torch.Size([2, 1, 5])


In [1]:
user_profile = {
    "username": "coder123",
    "level": 5,
    "is_active": True
}

In [5]:
a= user_profile.items()
print(user_profile.items())
print(type(a))

dict_items([('username', 'coder123'), ('level', 5), ('is_active', True)])
<class 'dict_items'>


In [6]:
b = list(user_profile.items())
print(list(user_profile.items()))
print(type(b))

[('username', 'coder123'), ('level', 5), ('is_active', True)]
<class 'list'>


In [8]:
for hari in user_profile.items():
    print (hari)


('username', 'coder123')
('level', 5)
('is_active', True)


In [ ]:
# let me try to recall self attention today- i think that i haven't learnt it in full depth.
#17.6.26

17.6

In [19]:
import torch
inputs = torch.tensor(
    [[0.43,0.15,0.89], #your
     [0.55,0.87,0.66],#journey
     [0.57,0.85,0.64],#starts
     [0.22,0.58,0.33],
     [0.77,0.25,0.10],
     [0.05,0.80,0.55]]
)

In [20]:
# first we find the attentions score of say input[2]
print(inputs.shape)

num_token= inputs.shape[0]
token_dim = inputs.shape[1]

torch.Size([6, 3])


In [21]:
torch.dot(inputs[0], inputs[1])

tensor(0.9544)

In [26]:
attn_score= torch.rand(1,num_token)
print(attn_score)

tensor([[0.7702, 0.5356, 0.6542, 0.4485, 0.0750, 0.8588]])


In [31]:
hari= torch.dot(inputs[0],inputs[2])
hari

tensor(0.9422)

In [ ]:
inputs[2]


tensor([0.5700, 0.8500, 0.6400])

In [38]:
num_token

6

In [52]:
torch.manual_seed(123)
attn_score= torch.rand(1,num_token)

In [53]:
attn_score

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665]])

In [54]:
attn_score[0]

tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665])

In [57]:
attn_score[0][1]

tensor(0.5166)

In [55]:
attn_score[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [40]:
attn_score[4]=4

IndexError: index 4 is out of bounds for dimension 0 with size 1

In [39]:
attn_score[5]= 3

IndexError: index 5 is out of bounds for dimension 0 with size 1

In [ ]:

for b in range(0,num_token ):
    # 
    # attn_score[b]=b
    # print(b)
    # oh!now i get this, we have formed a 2d matrix not an array
    attn_score[0][b]= torch.dot(inputs[0], inputs[b])

print(attn_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310]])


In [60]:
# and they used enumerate, lets seee that aslo
input_query= inputs[0]
for idx, token in enumerate(inputs):
    attn_score[0][idx]= torch.dot(input_query, token)

attn_score


tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310]])

In [62]:
hari= torch.rand(6)
hari      

# ohhhh, now we made an array

tensor([0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274])

In [66]:
# now we have to do for the whole matrix
# lets first make the attn_score_full
attn_score_full = torch.ones(inputs.shape[0], inputs.shape[0])
attn_score_full

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
for a in range(0,inputs.shape[0]):
    for idx, token in enumerate(inputs):
        attn_score_full[a][idx]= torch.dot(inputs[a], token)

attn_score_full
# haribol!!! we got it

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [68]:
# now lets try by matrix
attn_score_full_m = torch.ones(inputs.shape[0], inputs.shape[0])

In [70]:
attn_score_full_m = inputs @ inputs.transpose(-1,-2)
attn_score_full_m

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [71]:
attn_wts = torch.ones(inputs.shape[0], inputs.shape[0])

In [76]:
test= torch.rand(4)
print(test)
hari= torch.softmax(test, dim=0)
print(hari)
print(hari.sum())

tensor([0.9156, 0.4340, 0.0772, 0.3565])
tensor([0.3814, 0.2356, 0.1649, 0.2181])
tensor(1.)


In [ ]:
# now we have to normalise - or softmax

attn_wts= torch.softmax(attn_score_full_m, dim=1)
print(attn_wts)
print(attn_wts.sum(dim = -1))

# oh wow we have got this one also... now just one more step- the value step

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [80]:
# OH NOW we'll find the wts
context_vec = torch.ones(inputs.shape[0], inputs.shape[0])
context_vec= attn_wts @ inputs
context_vec

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

In [94]:
# now we'll use qkv and will directly make the class for this
import torch.nn as nn


attn_score= torch.rand(inputs.shape[0], inputs.shape[0])

class SelfAttention(nn.Module):
    def __init__(self, din, dout,bias= False):
        super().__init__()
        # din= jo hai
        # dout= the dimension that we want from the q k matrices
        # since there are traninable, we'll use nn.linear-> nn.parameter is not very nice

        self.Q= torch.nn.Linear(din, dout, bias)
        self.K = torch.nn.Linear(din, dout, bias)
        self.V= torch.nn.Linear(din,dout, bias) # ---> we could have made it of some other size also, but for now lets take this only

    def forward(self,x):
        keys = self.K(x)
        queries = self.Q(x)
        values = self.V(x)

        attn_score = queries @ keys.transpose(-1,-2)
        # now take the softmax
        attn_wts = torch.softmax(
            attn_score/keys.shape[-1]**0.5, dim=1)
        
        context_vec = attn_wts @ values
        return context_vec


In [95]:
sa= SelfAttention(3,2, False)
print(sa(inputs))

tensor([[0.4013, 0.1289],
        [0.4032, 0.1286],
        [0.4032, 0.1286],
        [0.4076, 0.1352],
        [0.4052, 0.1322],
        [0.4074, 0.1347]], grad_fn=<MmBackward0>)


now causal self attention only means that we have to make a mask- via the register buffer

In [98]:
mat_1 = torch.tensor([[1, 2, 3],
                      [4, 3, 8],
                      [1, 7, 2]])

mat_2 = torch.tensor([[2, 4, 1],
                      [1, 3, 6],
                      [2, 6, 5]])

out = mat_1 * mat_2

print(out)

tensor([[ 2,  8,  3],
        [ 4,  9, 48],
        [ 2, 42, 10]])
